format = """
[î‚¶](#cc241d)\
$os\
$username\
[î‚°](bg:#3c3836 fg:#cc241d)\
$directory\
[î‚°](fg:#3c3836 bg:#3c3836)\
$git_branch\
$git_status\
[î‚°](fg:#3c3836 bg:#7c6f64)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$python\
$scala\
[î‚°](fg:#7c6f64 bg:#cc241d)\
$docker_context\
[î‚°](fg:#cc241d bg:#3c3836)\
$time\
[î‚° ](fg:#cc241d)\
"""

[username]
show_always = true
style_user = "bg:#cc241d fg:#ebdbb2"
style_root = "bg:#cc241d fg:#ebdbb2"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#7c6f64 fg:#ebdbb2"
disabled = true

[directory]
style = "bg:#3c3836 fg:#ebdbb2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[c]
symbol = "î˜ "
style = "bg:#7c6f64 fg:#ebdbb2"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#7c6f64 fg:#ebdbb2"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = "î‰µ "
style = "bg:#7c6f64 fg:#ebdbb2"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#7c6f64 fg:#ebdbb2"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ğŸ˜¿ï˜"
style = "bg:#3c3836 fg:#d79921"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#3c3836 fg:#ebdbb2"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#7c6f64 fg:#ebdbb2"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#7c6f64 fg:#ebdbb2"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#7c6f64 fg:#ebdbb2"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#7c6f64 fg:#ebdbb2"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#7c6f64 fg:#ebdbb2"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#7c6f64 fg:#ebdbb2"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ó°†¥ "
style = "bg:#7c6f64 fg:#ebdbb2"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#7c6f64 fg:#ebdbb2"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "ğŸ"
style = "bg:#7c6f64 fg:#ebdbb2"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "bg:#7c6f64 fg:#ebdbb2"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#3c3836 fg:#ebdbb2"
format = '[ ğŸš€ğŸ’œ $time ]($style)'
